# Generated by Django 5.2.7 on 2025-10-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipient',
            options={'ordering': ['email']},
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='name',
        ),
        migrations.RemoveField(
            model_name='recipient',
            name='tags',
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='Use {{email}}, {{company}} for personalization'),
        ),
    ]
