# Generated by Django 5.2.7 on 2025-10-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_alter_recipient_options_remove_recipient_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive name for this credential set', max_length=200)),
                ('provider', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook/Office 365'), ('yahoo', 'Yahoo Mail'), ('custom', 'Custom SMTP')], default='gmail', max_length=50)),
                ('email_host', models.CharField(default='smtp.gmail.com', max_length=200)),
                ('email_port', models.IntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_use_ssl', models.BooleanField(default=False)),
                ('email_host_user', models.EmailField(help_text='Your email address', max_length=254)),
                ('email_host_password', models.TextField(help_text='Encrypted password/app password')),
                ('from_email', models.EmailField(help_text='Default sender email (usually same as host user)', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Use this credential for sending emails')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
    ]
