# Generated by Django 5.2.7 on 2025-10-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_delay', models.FloatField(default=0.0, help_text='Delay in seconds between sending each email (0 = no delay, max 60 seconds)')),
                ('batch_size', models.IntegerField(default=0, help_text='Number of emails to send before taking a longer pause (0 = no batching)')),
                ('batch_delay', models.FloatField(default=0.0, help_text='Delay in seconds after sending a batch (0 = no delay)')),
                ('max_attachments', models.IntegerField(default=5, help_text='Maximum number of attachments per email')),
                ('max_attachment_size', models.IntegerField(default=10, help_text='Maximum size per attachment in MB')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
        migrations.AddField(
            model_name='emaillog',
            name='attachment_count',
            field=models.IntegerField(default=0, help_text='Number of attachments sent'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='has_attachments',
            field=models.BooleanField(default=False, help_text='Whether this email had attachments'),
        ),
    ]
